/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.storehouse.frames;

import es.storehouse.models.StoreException;
import es.storehouse.models.User;
import es.storehouse.mysql.MySQLUserDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dquintero
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() throws StoreException {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_userName = new RSMaterialComponent.RSTextFieldIconTwo();
        txt_password = new RSMaterialComponent.RSPasswordIconTwo();
        combo_showPassword = new RSMaterialComponent.RSRadioButtonMaterial();
        btn_close = new RSMaterialComponent.RSButtonIconTwo();
        btn_login1 = new RSMaterialComponent.RSButtonMaterialTwo();
        lbl_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_userName.setBackground(new java.awt.Color(32, 51, 46));
        txt_userName.setForeground(new java.awt.Color(108, 140, 110));
        txt_userName.setText("Nombre de Usuario");
        txt_userName.setBorderColor(new java.awt.Color(108, 140, 110));
        txt_userName.setColorIcon(new java.awt.Color(108, 140, 110));
        txt_userName.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON);
        txt_userName.setPhColor(new java.awt.Color(108, 140, 110));
        txt_userName.setPlaceholder("Nombre de Usuario");
        txt_userName.setSelectionColor(new java.awt.Color(108, 140, 110));
        txt_userName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_userNameMouseClicked(evt);
            }
        });
        getContentPane().add(txt_userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        txt_password.setBackground(new java.awt.Color(32, 51, 46));
        txt_password.setForeground(new java.awt.Color(108, 140, 110));
        txt_password.setText("Clave de usuario");
        txt_password.setBorderColor(new java.awt.Color(108, 140, 110));
        txt_password.setColorIcon(new java.awt.Color(108, 140, 110));
        txt_password.setPhColor(new java.awt.Color(108, 140, 110));
        txt_password.setPlaceholder("Clave de usuario");
        txt_password.setSelectionColor(new java.awt.Color(108, 140, 110));
        txt_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_passwordMouseClicked(evt);
            }
        });
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        combo_showPassword.setForeground(new java.awt.Color(108, 140, 110));
        combo_showPassword.setText("Mostrar Contraseña");
        combo_showPassword.setColorCheck(new java.awt.Color(108, 140, 110));
        combo_showPassword.setColorUnCheck(new java.awt.Color(108, 140, 110));
        combo_showPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combo_showPassword.setRippleColor(new java.awt.Color(255, 255, 255));
        combo_showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_showPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(combo_showPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 230, 30));

        btn_close.setBackground(new java.awt.Color(108, 140, 110));
        btn_close.setBackgroundHover(new java.awt.Color(108, 140, 110));
        btn_close.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 30, 30));

        btn_login1.setBackground(new java.awt.Color(108, 140, 110));
        btn_login1.setText("Ingresar");
        btn_login1.setBackgroundHover(new java.awt.Color(108, 140, 110));
        btn_login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, -1));

        lbl_background.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("login.jpg")));
        getContentPane().add(lbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_userNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_userNameMouseClicked
        // TODO add your handling code here:
        txt_userName.setText("");
    }//GEN-LAST:event_txt_userNameMouseClicked

    private void txt_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_passwordMouseClicked
        // TODO add your handling code here:
        txt_password.setText("");
    }//GEN-LAST:event_txt_passwordMouseClicked

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void combo_showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_showPasswordActionPerformed
        // TODO add your handling code here:
        if (!combo_showPassword.isSelected()) {
            txt_password.setEchoChar('\u25cf');
        } else {
            txt_password.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_combo_showPasswordActionPerformed

    private void btn_login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login1ActionPerformed
        // TODO add your handling code here:
        String userName = txt_userName.getText();
        String password = String.valueOf(txt_password.getPassword());

        User user = new User(userName, password);

        MySQLUserDAO userDAO = new MySQLUserDAO();

        if (this.isShowing()) {
            try {

                if (userDAO.login(userName, password)) {
                    new Principal().setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Credenciales Invalida", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } catch (StoreException ex) {
                
            }

        }
    }//GEN-LAST:event_btn_login1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LogIn().setVisible(true);
                } catch (StoreException ex) {
                    Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonIconTwo btn_close;
    private RSMaterialComponent.RSButtonMaterialTwo btn_login1;
    private RSMaterialComponent.RSRadioButtonMaterial combo_showPassword;
    private javax.swing.JLabel lbl_background;
    private RSMaterialComponent.RSPasswordIconTwo txt_password;
    private RSMaterialComponent.RSTextFieldIconTwo txt_userName;
    // End of variables declaration//GEN-END:variables
}
