/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.storehouse.frames;

import es.storehouse.models.Provider;
import es.storehouse.models.StoreException;
import es.storehouse.mysql.MySQLProviderDAO;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dquintero
 */
public final class Providers extends javax.swing.JInternalFrame {

    DefaultTableModel model;
    ArrayList<Object[]> data = new ArrayList<>();

    /**
     * Creates new form Providers
     */
    public Providers() {
        initComponents();
        fillData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_productName = new RSMaterialComponent.RSLabelTextIcon();
        lbl_id = new RSMaterialComponent.RSLabelTextIcon();
        txt_id = new necesario.TextField();
        txt_providerName = new necesario.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        providerTable = new RSMaterialComponent.RSTableMetroCustom(){
            public boolean isCellEditable(int row, int column){
                return false;
            }

        };
        btn_insertProduct = new RSMaterialComponent.RSButtonMaterialIconTwo();
        btn_deleteProduct = new RSMaterialComponent.RSButtonMaterialIconTwo();
        btn_UpdateProduct = new RSMaterialComponent.RSButtonMaterialIconTwo();
        btn_cancel = new RSMaterialComponent.RSButtonMaterialIconTwo();

        setClosable(true);
        setTitle("Proveedores");

        lbl_productName.setForeground(new java.awt.Color(32, 51, 46));
        lbl_productName.setText("Proveedor:");
        lbl_productName.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        lbl_productName.setIcons(null);

        lbl_id.setForeground(new java.awt.Color(32, 51, 46));
        lbl_id.setText("ID:");
        lbl_id.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        lbl_id.setIcons(null);

        txt_id.setEditable(false);
        txt_id.setBackground(new java.awt.Color(255, 255, 255));
        txt_id.setForeground(new java.awt.Color(32, 51, 46));
        txt_id.setEnabled(false);
        txt_id.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_id.setPlaceholder("");
        txt_id.setSelectionColor(new java.awt.Color(32, 51, 46));

        txt_providerName.setForeground(new java.awt.Color(32, 51, 46));
        txt_providerName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_providerName.setPlaceholder("");
        txt_providerName.setSelectionColor(new java.awt.Color(32, 51, 46));

        providerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Proveedor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        providerTable.setBackgoundHead(new java.awt.Color(32, 51, 46));
        providerTable.setBackgoundHover(new java.awt.Color(32, 51, 46));
        providerTable.setColorPrimaryText(new java.awt.Color(32, 51, 46));
        providerTable.setColorSecundaryText(new java.awt.Color(32, 51, 46));
        providerTable.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        providerTable.setFontHead(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        providerTable.setFontRowHover(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        providerTable.setFontRowSelect(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        providerTable.setSelectionBackground(new java.awt.Color(108, 140, 110));
        providerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                providerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(providerTable);

        btn_insertProduct.setBackground(new java.awt.Color(32, 51, 46));
        btn_insertProduct.setText("Insertar Proveedor");
        btn_insertProduct.setBackgroundHover(new java.awt.Color(32, 51, 46));
        btn_insertProduct.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        btn_insertProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertProductActionPerformed(evt);
            }
        });

        btn_deleteProduct.setBackground(new java.awt.Color(32, 51, 46));
        btn_deleteProduct.setText("Eliminar Proveedor");
        btn_deleteProduct.setBackgroundHover(new java.awt.Color(32, 51, 46));
        btn_deleteProduct.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        btn_deleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteProductActionPerformed(evt);
            }
        });

        btn_UpdateProduct.setBackground(new java.awt.Color(32, 51, 46));
        btn_UpdateProduct.setText("Actualizar Proveedor");
        btn_UpdateProduct.setBackgroundHover(new java.awt.Color(32, 51, 46));
        btn_UpdateProduct.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        btn_UpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateProductActionPerformed(evt);
            }
        });

        btn_cancel.setBackground(new java.awt.Color(32, 51, 46));
        btn_cancel.setText("Cancelar");
        btn_cancel.setBackgroundHover(new java.awt.Color(32, 51, 46));
        btn_cancel.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CANCEL);
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1350, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_productName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_providerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(230, 230, 230)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_insertProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_deleteProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_UpdateProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_productName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_providerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_insertProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_deleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_UpdateProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void providerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_providerTableMouseClicked
        // TODO add your handling code here:
        txt_id.setText(providerTable.getValueAt(providerTable.getSelectedRow(), 0).toString());
        txt_providerName.setText(providerTable.getValueAt(providerTable.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_providerTableMouseClicked

    void clearTextField() {
        txt_providerName.setText("");
        txt_id.setText("");
    }

    void fillData() {
        String[] columns = new String[]{"ID", "Proveedor"};
        model = new DefaultTableModel(null, columns);

        MySQLProviderDAO providerDAO = new MySQLProviderDAO();

        try {
            data = providerDAO.obtainAll();
            data.forEach(row -> model.addRow(row));
            providerTable.setModel(model);

        } catch (StoreException e) {
            model.setRowCount(0);
        }
    }

    private void btn_insertProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertProductActionPerformed
        // TODO add your handling code here:

        String providerName = txt_providerName.getText();

        Provider p = new Provider(providerName);
        p.setName(providerName);

        MySQLProviderDAO productDAO = new MySQLProviderDAO();

        try {
            productDAO.insert(p);

        } catch (StoreException ex) {
            fillData();
            clearTextField();
        }

    }//GEN-LAST:event_btn_insertProductActionPerformed

    private void btn_deleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteProductActionPerformed
        // TODO add your handling code here:
        MySQLProviderDAO productDAO = new MySQLProviderDAO();
        int id = Integer.parseInt(txt_id.getText());

        Provider p = new Provider(id);
        p.setProviderId(id);

        try {
            productDAO.delete(p);
        } catch (StoreException ex) {

            fillData();
            providerTable.clearSelection();
            clearTextField();

        }
    }//GEN-LAST:event_btn_deleteProductActionPerformed

    private void btn_UpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateProductActionPerformed
        // TODO add your handling code here:
        MySQLProviderDAO productDAO = new MySQLProviderDAO();

        int providerId = Integer.parseInt(txt_id.getText());
        String providerName = txt_providerName.getText();

        Provider p = new Provider(providerId, providerName);
        p.setName(providerName);
        p.setProviderId(providerId);

        try {

            productDAO.update(p);

        } catch (StoreException ex) {
            fillData();
            providerTable.clearSelection();
            clearTextField();
        }
    }//GEN-LAST:event_btn_UpdateProductActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        providerTable.clearSelection();
        clearTextField();
    }//GEN-LAST:event_btn_cancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconTwo btn_UpdateProduct;
    private RSMaterialComponent.RSButtonMaterialIconTwo btn_cancel;
    private RSMaterialComponent.RSButtonMaterialIconTwo btn_deleteProduct;
    private RSMaterialComponent.RSButtonMaterialIconTwo btn_insertProduct;
    private javax.swing.JScrollPane jScrollPane1;
    private RSMaterialComponent.RSLabelTextIcon lbl_id;
    private RSMaterialComponent.RSLabelTextIcon lbl_productName;
    private RSMaterialComponent.RSTableMetroCustom providerTable;
    private necesario.TextField txt_id;
    private necesario.TextField txt_providerName;
    // End of variables declaration//GEN-END:variables
}
